

package org.jetbrains.kotlin.compiler.plugin.template.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.compiler.plugin.template.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class JvmDiagnosticTestGenerated extends AbstractJvmDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("allIgnored.kt")
  public void testAllIgnored() {
    runTest("compiler-plugin/testData/diagnostics/allIgnored.kt");
  }

  @Test
  @TestMetadata("anotherDiagnosticTest.kt")
  public void testAnotherDiagnosticTest() {
    runTest("compiler-plugin/testData/diagnostics/anotherDiagnosticTest.kt");
  }

  @Test
  @TestMetadata("ignore.kt")
  public void testIgnore() {
    runTest("compiler-plugin/testData/diagnostics/ignore.kt");
  }

  @Test
  @TestMetadata("ignoreMissingDataFlowAnnotation.kt")
  public void testIgnoreMissingDataFlowAnnotation() {
    runTest("compiler-plugin/testData/diagnostics/ignoreMissingDataFlowAnnotation.kt");
  }
}
